spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          #Git SSH configuration using properties (PARA GIT PRIVADO)
          uri: https://github.com/DaxB9/ConfigServer
          default-label: "main"
server:
  port: 8888

